name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: '8'
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip build-essential git wget unzip
        pip install --upgrade cython
        pip install buildozer
        echo "Adding Buildozer to PATH"
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        
    - name: Set up Android SDK
      env:
        ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk
      run: |
        mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-7302050_latest.zip -O commandlinetools.zip
        unzip commandlinetools.zip -d $ANDROID_SDK_ROOT/cmdline-tools
        mv $ANDROID_SDK_ROOT/cmdline-tools/cmdline-tools $ANDROID_SDK_ROOT/cmdline-tools/latest
        yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses
        $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --update
        $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-30" "build-tools;30.0.3"
        
    - name: Build APK
      env:
        ANDROID_HOME: ${{ github.workspace }}/android-sdk
        PATH: ${{ github.workspace }}/android-sdk/platform-tools:${{ github.workspace }}/android-sdk/cmdline-tools/latest/bin:$HOME/.local/bin:$PATH
      run: |
        buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: my-app-debug.apk
        path: bin/*.apk
